In [1]:
import pandas as pd
import numpy as np

In [2]:
excel_name = '成本核算数据源配置表.xlsx'
sheet_name = {
    'source': {
        'revenue': '收入',
        'spend':'投放费',
        'timesheet':'项目工时',
        'employee':'人员工资奖金五险一金',
        'cloud':'云服务费',
        'technical':'技术服务费',
        'operation':'运营费用',
        'bjdepartment':'北京天天部门费用',
        'cddepartment':'成都天天部门费用',
    },
    'config': {
        'employee':'人员费用配置表',
        'project':'项目费用配置表'
    }
}

In [3]:
revenue = pd.read_excel(excel_name, sheet_name=sheet_name['source']['revenue'])
revenue

,收入类型,项目收入占比,纸牌-Collection Fish,纸牌-Solitaire 3D Fish,纸牌-Solitaire Dragons,纸牌-Solitaire Fish,纸牌-Spider Fish,纸牌-Tripeaks Fish,纸牌-Solitaire Farm Friends,纸牌-Solitaire Garden,...,智力-Breaker Fun,智力-Breaker Fun 2,智力-Tile Farm,智力-Tile Match,智力-Sort Fun,智力-Tile Travel 3D,智力-Merge Cooking,纸牌-Tripeaks Lucky,智力-Dice Merge,智力-Tile Artist
0,广告,收入,50000.0,40000.0,30000.0,40000.0,50000.0,40000.0,30000.0,40000.0,...,40000.0,50000.0,40000.0,30000.0,40000.0,50000.0,40000.0,30000.0,40000.0,40000
1,NaN,占比,5.0,4.0,3.0,4.0,5.0,4.0,3.0,4.0,...,4.0,5.0,4.0,3.0,4.0,5.0,4.0,3.0,4.0,4
2,内购,收入,60000.0,50000.0,40000.0,30000.0,20000.0,30000.0,40000.0,50000.0,...,50000.0,60000.0,50000.0,40000.0,30000.0,20000.0,30000.0,40000.0,50000.0,40000
3,NaN,占比,6.0,5.0,4.0,3.0,2.0,3.0,4.0,5.0,...,5.0,6.0,5.0,4.0,3.0,2.0,3.0,4.0,5.0,4
4,合计,收入,55000.0,45000.0,35000.0,35000.0,35000.0,35000.0,35000.0,45000.0,...,45000.0,55000.0,45000.0,35000.0,35000.0,35000.0,35000.0,35000.0,45000.0,40000
5,NaN,占比,5.5,4.5,3.5,3.5,3.5,3.5,3.5,4.5,...,4.5,5.5,4.5,3.5,3.5,3.5,3.5,3.5,4.5,4

In [4]:
revenue = revenue.fillna(method='ffill')
revenue_adv = revenue[revenue['收入类型'] == '广告']
revenue_inapp = revenue[revenue['收入类型'] == '内购']
revenue = revenue[revenue['收入类型'] == '合计']
revenue_adv.set_index('项目收入占比',inplace=True)
revenue_inapp.set_index('项目收入占比',inplace=True)
revenue.set_index('项目收入占比',inplace=True)
revenue

,收入类型,纸牌-Collection Fish,纸牌-Solitaire 3D Fish,纸牌-Solitaire Dragons,纸牌-Solitaire Fish,纸牌-Spider Fish,纸牌-Tripeaks Fish,纸牌-Solitaire Farm Friends,纸牌-Solitaire Garden,纸牌-Solitaire Resort,...,智力-Breaker Fun,智力-Breaker Fun 2,智力-Tile Farm,智力-Tile Match,智力-Sort Fun,智力-Tile Travel 3D,智力-Merge Cooking,纸牌-Tripeaks Lucky,智力-Dice Merge,智力-Tile Artist
项目收入占比,,,,,,,,,,,,,,,,,,,,,
收入,合计,55000.0,45000.0,35000.0,35000.0,35000.0,35000.0,35000.0,45000.0,55000.0,...,45000.0,55000.0,45000.0,35000.0,35000.0,35000.0,35000.0,35000.0,45000.0,40000
占比,合计,5.5,4.5,3.5,3.5,3.5,3.5,3.5,4.5,5.5,...,4.5,5.5,4.5,3.5,3.5,3.5,3.5,3.5,4.5,4

In [5]:
revenue_percent = revenue.loc['占比'][1:]
revenue_percent_df = pd.DataFrame(revenue_percent)
revenue_percent_df

                            占比
纸牌-Collection Fish         5.5
纸牌-Solitaire 3D Fish       4.5
纸牌-Solitaire Dragons       3.5
纸牌-Solitaire Fish          3.5
纸牌-Spider Fish             3.5
纸牌-Tripeaks Fish           3.5
纸牌-Solitaire Farm Friends  3.5
纸牌-Solitaire Garden        4.5
纸牌-Solitaire Resort        5.5
纸牌-Solitaire Club          4.5
纸牌-Solitaire Dark Mode     3.5
智力-Block Fish              3.5
智力-Block Farm              3.5
智力-Woody Dice Merge        3.5
智力-Royal Breaker           3.5
智力-Breaker Fun             4.5
智力-Breaker Fun 2           5.5
智力-Tile Farm               4.5
智力-Tile Match              3.5
智力-Sort Fun                3.5
智力-Tile Travel 3D          3.5
智力-Merge Cooking           3.5
纸牌-Tripeaks Lucky          3.5
智力-Dice Merge              4.5
智力-Tile Artist               4

In [6]:
cloud = pd.read_excel(excel_name, sheet_name=sheet_name['source']['cloud'])
cloud.set_index('费用项',inplace=True)
cloud

                      费用
费用项
北京天天阿里云服务费          1000
北京天天Google云服务费      2000
成都天天阿里云服务费          2000
成都天天Google和AWS云服务费  2000
成都某一项目云服务费          1000

In [7]:
project_config = pd.read_excel(excel_name, sheet_name=sheet_name['config']['project'])
project_config.columns = list(project_config.columns.values[0:4]) + list(project_config.loc[0][4:].values)
project_config = project_config.drop(0).fillna(0)
project_config.set_index('项目', inplace= True)
project_config

NameError: name 'pg' is not defined

In [ ]:
project_config_fee = pd.merge(project_config,revenue_percent_df, left_index=True, right_index=True, how='left')
print('数据清洗完毕')
print('开启数据计算')

In [ ]:
project_config_fee